/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.Enterprise.Enterprise;
import Business.Organization.DistributorOrganization;
import Business.Organization.NGOAdminOrganization;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.Organization.OrganizationDirectory;
import Business.Organization.QualityOrganization;
import Business.Organization.ShelterOrganization;
import Business.Organization.SupplierOrganization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author db
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrganizationJPanel
     */
    private JPanel userProcessContainer;
    private OrganizationDirectory organizationDirectory;
    private Enterprise enterprise;
    
    public ManageOrganizationJPanel() {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDirectory = organizationDirectory;
        this.enterprise = enterprise;
        populateTable();
        populateComboBox();
    }

    ManageOrganizationJPanel(JPanel userProcessContainer, OrganizationDirectory organizationDirectory, Enterprise enterprise) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrganizations = new javax.swing.JTable();
        btnAddOrganization = new javax.swing.JButton();
        organizationJComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 102));

        tblOrganizations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrganizations);

        btnAddOrganization.setBackground(new java.awt.Color(255, 255, 255));
        btnAddOrganization.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnAddOrganization.setText("Add Organization");
        btnAddOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrganizationActionPerformed(evt);
            }
        });

        organizationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationJComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("List Of Organizations");

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Organization Type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 70, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(organizationJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(322, 322, 322))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnAddOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(organizationJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(106, 106, 106)
                .addComponent(btnAddOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrganizationActionPerformed

         Type type = (Type) organizationJComboBox.getSelectedItem();
        organizationDirectory.createOrganization(type);
        populateTable();

        JOptionPane.showMessageDialog(null, "Organization added successfully!");
    }//GEN-LAST:event_btnAddOrganizationActionPerformed
private void populateTable() {

        DefaultTableModel model = (DefaultTableModel) tblOrganizations.getModel();

        model.setRowCount(0);

        for (Organization organization : organizationDirectory.getOrganizationList()) {
            Object[] row = new Object[2];
            row[0] = organization.getOrganizationID();
            row[1] = organization.getName();

            model.addRow(row);
        }

    }
    private void organizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationJComboBoxActionPerformed
        // TODO add your handling code here:
        /*
        organizationJComboBox.removeAllItems();

        for(Organization.Type type: Organization.Type.values())
        {

            if(enterprise.getEnterpriseType().getValue().equals(Enterprise.EnumType1.NGO.getValue()))
            {
                if(type.getValue().equals(Organization.Type.NgoFoodOrganization.getValue()))
                {
                    organizationJComboBox.addItem(type);
                }
            }

            else if(enterprise.getEnterpriseType().getValue().equals(Enterprise.EnumType2.Shelter.getValue()))
            {
                if(type.getValue().equals(Organization.Type.ShelterFoodOrganization.getValue()))
                {
                    organizationJComboBox.addItem(type);
                }
            }

            else if(enterprise.getEnterpriseType().getValue().equals(Enterprise.EnumType3.Distributor.getValue()))
            {
                if(type.getValue().equals(Organization.Type.DistributorFoodOrganization.getValue()))
                {
                    organizationJComboBox.addItem(type);
                }
            }

            else if(enterprise.getEnterpriseType().getValue().equals(Enterprise.EnumType4.QualityCheck.getValue()))
            {
                if(type.getValue().equals(Organization.Type.QualityCheckFoodOrganization.getValue()))
                {
                    organizationJComboBox.addItem(type);
                }
            }

            else if(enterprise.getEnterpriseType().getValue().equals(Enterprise.EnumType5.Supplier.getValue()))
            {
                if(type.getValue().equals(Organization.Type.SupplierFoodOrganization.getValue()))
                {
                    organizationJComboBox.addItem(type);
                }
            }

        }
        */
    }//GEN-LAST:event_organizationJComboBoxActionPerformed
private void populateComboBox() {

//        organizationJComboBox.removeAllItems();
//        for (Type type : Organization.Type.values()){
//            if (!type.getValue().equals(Type.Admin.getValue()))
//                organizationJComboBox.addItem(type);
//        } 
        /*for (Type type : Organization.Type.values()){
        System.out.println(type);
             System.out.println(Enterprise.EnterpriseType.Rehabilitation);
        if((!type.getValue().equals(Type.Admin.getValue())) && (enterprise.getEnterpriseType().equals("NGO"))){
            organizationJComboBox.addItem(type);
        }
        else if ((!type.getValue().equals(Type.Admin.getValue()))&&(enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Pharmacy))) {
            organizationJComboBox.addItem(type);
        }
        else if ((!type.getValue().equals(Type.Admin.getValue()))&&(enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.DrugSupplier))) {
            organizationJComboBox.addItem(type);
        }
         */
        organizationJComboBox.removeAllItems();

//        for (Organization.Type type : Organization.Type.values()) {
//
//            if (enterprise.getEnterpriseType().getValue().equals(Enterprise.EnumType1.NGO.getValue())) {
//                if (type.getValue().equals(Organization.Type.NgoFoodOrganization.getValue())) {
//                    organizationJComboBox.addItem(type);
//                }
//            } else if (enterprise.getEnterpriseType().getValue().equals(Enterprise.EnumType2.Shelter.getValue())) {
//                if (type.getValue().equals(Organization.Type.ShelterFoodOrganization.getValue())) {
//                    organizationJComboBox.addItem(type);
//                }
//            } else if (enterprise.getEnterpriseType().getValue().equals(Enterprise.EnumType3.Distributor.getValue())) {
//                if (type.getValue().equals(Organization.Type.DistributorFoodOrganization.getValue())) {
//                    organizationJComboBox.addItem(type);
//                }
//            } else if (enterprise.getEnterpriseType().getValue().equals(Enterprise.EnumType4.QualityCheck.getValue())) {
//                if (type.getValue().equals(Organization.Type.QualityCheckFoodOrganization.getValue())) {
//                    organizationJComboBox.addItem(type);
//                }
//            } else if (enterprise.getEnterpriseType().getValue().equals(Enterprise.EnumType5.Supplier.getValue())) {
//                if (type.getValue().equals(Organization.Type.SupplierFoodOrganization.getValue())) {
//                    organizationJComboBox.addItem(type);
//                }
//            }
//
//        }
//        
//         System.out.println(enterprise.getEnterpriseType().toString()==(Enterprise.EnterpriseType.Shelter)+"check");
//        if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.NGO) {
//         
//            organizationJComboBox.addItem(Organization.Type.NgoFoodOrganization);
//           
//        } else if (enterprise.getEnterpriseType()== Enterprise.EnterpriseType.Distributor) {
//            organizationJComboBox.addItem(Organization.Type.DistributorFoodOrganization);
//        } else if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.QualityCheck) {
//            organizationJComboBox.addItem(Organization.Type.QualityCheckFoodOrganization);
//        } else if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.Shelter) {
//               System.out.println("Shelter check");
//            organizationJComboBox.addItem(Organization.Type.ShelterFoodOrganization);
//        } else if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.Supplier) {
//          
//            organizationJComboBox.addItem(Organization.Type.SupplierFoodOrganization);
//            
//        }
        System.out.println("yegdc" + enterprise.getEnterpriseType().getValue().equals(Enterprise.EnumType1.NGO.getValue()));
         System.out.println("yecfghgdc" + enterprise.getEnterpriseType().getValue());
        
          System.out.println("yfrtdrecfggvegdc" + Enterprise.EnumType1.NGO.getValue());
        
        
        if (enterprise.getEnterpriseType().getValue().equals(Enterprise.EnumType1.NGO.getValue())) {
            organizationJComboBox.addItem(Organization.Type.NgoFoodOrganization);
        } else if (enterprise.getEnterpriseType().getValue().equals(Enterprise.EnumType2.Shelter.getValue())) {
            organizationJComboBox.addItem(Organization.Type.ShelterFoodOrganization);
        } else if (enterprise.getEnterpriseType().getValue().equals(Enterprise.EnumType3.Distributor.getValue())) {
            organizationJComboBox.addItem(Organization.Type.DistributorFoodOrganization);
        } else if (enterprise.getEnterpriseType().getValue().equals(Enterprise.EnumType4.QualityCheck.getValue())) {
            organizationJComboBox.addItem(Organization.Type.QualityCheckFoodOrganization);
        } else if (enterprise.getEnterpriseType().getValue().equals(Enterprise.EnumType5.Supplier.getValue())) {
            organizationJComboBox.addItem(Organization.Type.SupplierFoodOrganization);
        }
}

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

       userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOrganization;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox organizationJComboBox;
    private javax.swing.JTable tblOrganizations;
    // End of variables declaration//GEN-END:variables
}
