/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PharmacyRole;

/**
 *
 * @author Sai Sravani
 */
public class ViewDetailsJPanel extends javax.swing.JPanel {

    /** Creates new form ViewDetailsJPanel */
    public ViewDetailsJPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serialNumLbl = new javax.swing.JLabel();
        serialNumTxtField = new javax.swing.JTextField();
        drugLbl = new javax.swing.JLabel();
        drugNameTxtField = new javax.swing.JTextField();
        medicineLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        serialNumLbl.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        serialNumLbl.setForeground(new java.awt.Color(0, 0, 102));
        serialNumLbl.setText("SERIAL NUMBER:");
        add(serialNumLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 230, 50));

        serialNumTxtField.setEditable(false);
        serialNumTxtField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        serialNumTxtField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(serialNumTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 230, 40));

        drugLbl.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        drugLbl.setForeground(new java.awt.Color(0, 0, 102));
        drugLbl.setText("Medicine Name:");
        add(drugLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 379, -1, 30));

        drugNameTxtField.setEditable(false);
        drugNameTxtField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        drugNameTxtField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(drugNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 383, 207, -1));

        medicineLbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 48)); // NOI18N
        medicineLbl.setForeground(new java.awt.Color(0, 0, 102));
        medicineLbl.setText("View Medicine Details");
        add(medicineLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 130, 540, 80));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 940, 810));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel drugLbl;
    private javax.swing.JTextField drugNameTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel medicineLbl;
    private javax.swing.JLabel serialNumLbl;
    private javax.swing.JTextField serialNumTxtField;
    // End of variables declaration//GEN-END:variables

}
