/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package DrugSupplier;

/**
 *
 * @author db
 */
public class AddDrugJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddDrugJPanel
     */
    private DrugList drugList;
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private DrugOrganization drugOrganization;
    private Enterprise enterprise;
    private Network network;
    private static Logger log = Logger.getLogger(AddDrugJPanel.class);
    private static final String CLASS_NAME = AddDrugJPanel.class.getName();

    public AddDrugJPanel() {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        this.enterprise = enterprise;
        this.network = network;
        this.drugOrganization = drugOrganization;
        populateTable();
    }
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) drugTble.getModel();

        model.setRowCount(0);

        for (Drug d : business.getDrugList().getDrugList()) {

            Object[] row = new Object[2];
            row[0] = d.getDrugId();
            row[1] = d;
            model.addRow(row);

        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
