/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package DrugSupplier;

/**
 *
 * @author db
 */
public class AddDrugJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddDrugJPanel
     */
    private DrugList drugList;
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private DrugOrganization drugOrganization;
    private Enterprise enterprise;
    private Network network;
    private static Logger log = Logger.getLogger(AddDrugJPanel.class);
    private static final String CLASS_NAME = AddDrugJPanel.class.getName();

    public AddDrugJPanel() {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        this.enterprise = enterprise;
        this.network = network;
        this.drugOrganization = drugOrganization;
        populateTable();
    }
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) drugTble.getModel();

        model.setRowCount(0);

        for (Drug d : business.getDrugList().getDrugList()) {

            Object[] row = new Object[2];
            row[0] = d.getDrugId();
            row[1] = d;
            model.addRow(row);

        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        processlbl = new javax.swing.JLabel();
        logolbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        drugTble = new javax.swing.JTable();
        drugtxtField = new javax.swing.JTextField();
        addDrugBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        addChemicalButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        processlbl.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        processlbl.setText("Drug Panel");
        add(processlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 300, 70));

        logolbl.setText("logo");
        add(logolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 60, 40));

        drugTble.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 20)); // NOI18N
        drugTble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DrugName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        drugTble.setRowHeight(30);
        jScrollPane1.setViewportView(drugTble);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 141, 720, 130));

        drugtxtField.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 20)); // NOI18N
        drugtxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugtxtFieldActionPerformed(evt);
            }
        });
        add(drugtxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 230, 40));

        addDrugBtn.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 20)); // NOI18N
        addDrugBtn.setText("ADD Drug");
        addDrugBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrugBtnActionPerformed(evt);
            }
        });
        add(addDrugBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 180, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 20)); // NOI18N
        jLabel3.setText("DRUG");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 123, 40));

        addChemicalButton.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 20)); // NOI18N
        addChemicalButton.setText("Add Chemical");
        addChemicalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addChemicalButtonActionPerformed(evt);
            }
        });
        add(addChemicalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, -1, -1));

        backButton.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 20)); // NOI18N
        backButton.setText(" Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void drugtxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugtxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drugtxtFieldActionPerformed

    private void addDrugBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrugBtnActionPerformed
        // TODO add your handling code here:

        String drugName = drugtxtField.getText().trim();
        if(drugName.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Drug name cannot be empty");
            return;
        }
        ArrayList<String> drugcheck= new ArrayList<>();
        for(Drug d:business.getDrugList().getDrugList())
        {
            drugcheck.add(d.getDrugName().toLowerCase());
        }
        if(drugcheck.contains(drugName.toLowerCase()))
        {
            JOptionPane.showMessageDialog(null,"Drug name already exists");
            return;
        }

        business.getDrugList().addDrugList().setDrugName(drugName);

        populateTable();
        log.debug(userAccount+" "+"added new drug"+" "+drugName);
        drugtxtField.setText("");
    }//GEN-LAST:event_addDrugBtnActionPerformed

    private void addChemicalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addChemicalButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = drugTble.getSelectedRow();
        if(selectedRow<0)
        {
            JOptionPane.showMessageDialog(null, "please select a row ");
            return;
        }
        Drug c = (Drug) drugTble.getValueAt(selectedRow, 1);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("AddChemicalsJPanel", new AddChemicalsJPanel(userProcessContainer, business, userAccount, drugOrganization, enterprise, network, c));
        log.debug(userAccount+" "+"entering add chemicals page");
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addChemicalButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addChemicalButton;
    private javax.swing.JButton addDrugBtn;
    private javax.swing.JButton backButton;
    private javax.swing.JTable drugTble;
    private javax.swing.JTextField drugtxtField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logolbl;
    private javax.swing.JLabel processlbl;
    // End of variables declaration//GEN-END:variables
}
