/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package DrugSupplier;

/**
 *
 * @author db
 */
public class GenerateDrugNewDrudJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GenerateDrugNewDrudJPanel
     */
    private JPanel userProcessContainer;
    private Patient patient;
    private DrugOrganization drugOrganization;
    private UserAccount userAccount;
    private Network network;
    private EcoSystem business;
    private static Logger log = Logger.getLogger(GenerateDrugNewDrugJPanel.class);
    private static final String CLASS_NAME = GenerateDrugNewDrugJPanel.class.getName();

    public GenerateDrugNewDrudJPanel() {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.patient = patient;
        this.drugOrganization = drugOrganization;
        this.userAccount = userAccount;
        this.network = network;
        this.business = business;
        patientTxtField.setText(patient.getPatientName());
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultLbl = new javax.swing.JLabel();
        logolbl = new javax.swing.JLabel();
        patientNameLbl = new javax.swing.JLabel();
        patientTxtField = new javax.swing.JTextField();
        jScrollPane = new javax.swing.JScrollPane();
        newDrugTbl = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        addnewdrugBtn = new javax.swing.JButton();
        newDrugTxt = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resultLbl.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        resultLbl.setText("New Drug");
        add(resultLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 29, -1, -1));

        logolbl.setText("logoo");
        add(logolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 50, 40));

        patientNameLbl.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        patientNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientNameLbl.setText("Patient Name :");
        add(patientNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 99, 170, 30));

        patientTxtField.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        patientTxtField.setEnabled(false);
        add(patientTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 99, 294, 30));

        newDrugTbl.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 20)); // NOI18N
        newDrugTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Gene", "Chemical Compound"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        newDrugTbl.setRowHeight(30);
        jScrollPane.setViewportView(newDrugTbl);

        add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 168, 650, 170));

        backBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 170, -1));

        addnewdrugBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addnewdrugBtn.setText("Add New Drug");
        addnewdrugBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewdrugBtnActionPerformed(evt);
            }
        });
        add(addnewdrugBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 220, 41));
        add(newDrugTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 267, 41));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LabResultsJpanel dwjp = (LabResultsJpanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void addnewdrugBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewdrugBtnActionPerformed
        // TODO add your handling code here:
        String drugName = newDrugTxt.getText().trim();
        if(drugName.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter the drug name");
            return;
        }
        ArrayList<String>drugCheck = new ArrayList<>();
        for(Drug d:business.getDrugList().getDrugList())
        {
            drugCheck.add(d.getDrugName().toLowerCase());
        }
        if(drugCheck.contains(drugName))
        {
            JOptionPane.showMessageDialog(null, " Drug name already exists ");
            return;
        }
        Drug d = business.getDrugList().addDrugList();
        d.setDrugName(drugName);
        patient.setNewDrug(drugName);
        int count = newDrugTbl.getRowCount();
        for (int i = 0; i < count; i++) {
            String s = newDrugTbl.getValueAt(i, 0).toString();
            d.getGeneHistory().addGeneList().setGeneName(s);
            String t = newDrugTbl.getValueAt(i, 1).toString();
            d.getChemicalList().addChemicalList().setChemicalName(t);

        }
        JOptionPane.showMessageDialog(null,"New Drug is added succesfully");
        log.debug(userAccount+" "+"added new drug"+" "+drugName);

    }//GEN-LAST:event_addnewdrugBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addnewdrugBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel logolbl;
    private javax.swing.JTable newDrugTbl;
    private javax.swing.JTextField newDrugTxt;
    private javax.swing.JLabel patientNameLbl;
    private javax.swing.JTextField patientTxtField;
    private javax.swing.JLabel resultLbl;
    // End of variables declaration//GEN-END:variables
}
