/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package DrugSupplier;

/**
 *
 * @author db
 */
public class GenerateDrugNewDrudJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GenerateDrugNewDrudJPanel
     */
    private JPanel userProcessContainer;
    private Patient patient;
    private DrugOrganization drugOrganization;
    private UserAccount userAccount;
    private Network network;
    private EcoSystem business;
    private static Logger log = Logger.getLogger(GenerateDrugNewDrugJPanel.class);
    private static final String CLASS_NAME = GenerateDrugNewDrugJPanel.class.getName();

    public GenerateDrugNewDrudJPanel() {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.patient = patient;
        this.drugOrganization = drugOrganization;
        this.userAccount = userAccount;
        this.network = network;
        this.business = business;
        patientTxtField.setText(patient.getPatientName());
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
